# Site settings
url: "https://augmentedperception.github.io"
baseurl: "/cvpr2025"
remote_theme: pages-themes/cayman@v0.2.0
title: Sense, Perceive, Interact & Render on Android XR
description: "[CVPR 2025 Tutorial]"

# GitHub settings
github:
  is_project_page: false

# Twitter-specific settings
twitter:
  card: summary_large_image

# Social media image
image: /assets/cvpr25_tutorial_social.png